/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "Api": {
      "type": "sst.aws.ApiGatewayV1"
      "url": string
    }
    "COGNITO_CLIENT_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "COGNITO_CLIENT_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "COGNITO_REGION": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "COGNITO_USER_POOL_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "JWT_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SMS_PROVIDER_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "STRAVA_CLIENT_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "STRAVA_CLIENT_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Users": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}