# Automatically generated by SST
# pylint: disable=all
from typing import Any

class Resource:
    class Api:
        type: str
        url: str
    class App:
        name: str
        stage: str
    class COGNITO_CLIENT_ID:
        type: str
        value: str
    class COGNITO_CLIENT_SECRET:
        type: str
        value: str
    class COGNITO_REGION:
        type: str
        value: str
    class COGNITO_USER_POOL_ID:
        type: str
        value: str
    class JWT_SECRET:
        type: str
        value: str
    class SMS_PROVIDER_API_KEY:
        type: str
        value: str
    class STRAVA_CLIENT_ID:
        type: str
        value: str
    class STRAVA_CLIENT_SECRET:
        type: str
        value: str
    class Users:
        name: str
        type: str

