default_agent: agent
agents:
  agent:
    name: agent
    entrypoint: src/agent.py
    platform: linux/arm64
    container_runtime: docker
    aws:
      execution_role: null
      execution_role_auto_create: true
      account: '366815213561'
      region: us-west-2
      ecr_repository: null
      ecr_auto_create: true
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: null
      agent_arn: null
      agent_session_id: 610c2574-397c-4569-8cb9-74bd80579a42
    codebuild:
      project_name: null
      execution_role: null
      source_bucket: null
    authorizer_configuration: null
    oauth_configuration:
      workload_name: workload-f488bd44
